### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython

### ISSUE THREAD

**Issue by leiwen83** [TAMU-VITA/AGD#14]
I meet below error in the first setup steps for "conda env create -f env.yml"
Do you have recommended docker file to reproduce your result?

Thx,
Lei

```
Pip subprocess error:
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bqohnt65/pycocotools/setup.py", line 2, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-bqohnt65/pycocotools/
```

**Comment by tilmto** [comment]
We didn't use a docker env for the exps since all the packages are commonly used ones without complex dependency. You can manually install Cython with `pip install Cython`, as well as other missing packages.
